version: 2.1
orbs:
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  build_and_test:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
      - checkout
      - run:
          name: Install packages
          command: |
            pip install boto3
      - run:
          name: Run tests
          command: python -m unittest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli
      - run:
          name: Zip Lambda function
          command: |
            mkdir lambda_func
            mkdir lambda_artifacts
            cd lambda_artifacts
            pip install --platform manylinux2014_x86_64 --target=package --implementation cp --only-binary=:all: --upgrade boto3
            zip -r ../lambda_func/lambda_function.zip .
            cd ..
            zip -j lambda_func/lambda_function.zip lambda_script/lambda_function.py
      - run:
          name: Dir
          command: |
            echo "$PWD"
            ls
      - run:
          name: Deploy Lambda function
          command: |
            export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY"
            export AWS_SECRET_ACCESS_KEY="$AWS_ACCESS_SECRET"
            export AWS_DEFAULT_REGION="$AWS_REGION_NAME"
            aws s3 sync glue_script s3://camesruiz-waddi/glue_script
            aws s3 sync lambda_func s3://camesruiz-waddi/lambda_script
            aws lambda update-function-code --function-name "waddi_data_ingestion" --s3-bucket "camesruiz-waddi" --s3-key "lambda_script/lambda_function.zip"

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
